/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Laptop
 */
public class Presentacion extends javax.swing.JFrame {

    
    private Color background = new Color(224, 221, 211);
    private Color secundary = new Color(255, 254, 250);
    private Color text = new Color(224, 221, 211);
    private Color hover = new Color(224, 221, 211);
    private Color resaltar = new Color(224, 221, 211);
    
    public Presentacion() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        uni = new javax.swing.JLabel();
        containerTitulo = new Clases.PanelRound();
        perfilCarlos = new javax.swing.JLabel();
        perfilKarla = new javax.swing.JLabel();
        perfilYasser = new javax.swing.JLabel();
        buttonIniciar = new Clases.PanelRound();
        iniciarLabel = new javax.swing.JLabel();
        buttonHelp = new Clases.PanelRound();
        helpLabel1 = new javax.swing.JLabel();
        helpLabel = new javax.swing.JLabel();
        helpLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        container.setBackground(new java.awt.Color(255, 255, 255));

        uni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/UNI-logo.png"))); // NOI18N
        uni.setText("jLabel7");

        containerTitulo.setBackground(new java.awt.Color(0, 153, 0));
        containerTitulo.setRoundBottomLeft(50);
        containerTitulo.setRoundBottomRight(50);
        containerTitulo.setRoundTopLeft(50);
        containerTitulo.setRoundTopRight(50);

        perfilCarlos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/chris.jpeg"))); // NOI18N

        perfilKarla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/fran.jpeg"))); // NOI18N

        perfilYasser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/sebas (1).jpg"))); // NOI18N

        buttonIniciar.setBackground(new java.awt.Color(255, 254, 250));
        buttonIniciar.setRoundBottomLeft(50);
        buttonIniciar.setRoundBottomRight(50);
        buttonIniciar.setRoundTopLeft(50);
        buttonIniciar.setRoundTopRight(50);
        buttonIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonIniciarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonIniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonIniciarMouseExited(evt);
            }
        });

        iniciarLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        iniciarLabel.setForeground(new java.awt.Color(78, 88, 97));
        iniciarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iniciarLabel.setText("Iniciar");

        javax.swing.GroupLayout buttonIniciarLayout = new javax.swing.GroupLayout(buttonIniciar);
        buttonIniciar.setLayout(buttonIniciarLayout);
        buttonIniciarLayout.setHorizontalGroup(
            buttonIniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonIniciarLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(iniciarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        buttonIniciarLayout.setVerticalGroup(
            buttonIniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonIniciarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iniciarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        buttonHelp.setBackground(new java.awt.Color(255, 254, 250));
        buttonHelp.setPreferredSize(new java.awt.Dimension(150, 50));
        buttonHelp.setRoundBottomLeft(50);
        buttonHelp.setRoundBottomRight(50);
        buttonHelp.setRoundTopLeft(50);
        buttonHelp.setRoundTopRight(50);
        buttonHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonHelpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonHelpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonHelpMouseExited(evt);
            }
        });

        helpLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        helpLabel1.setForeground(new java.awt.Color(78, 88, 97));
        helpLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        helpLabel1.setText("Ayuda");

        javax.swing.GroupLayout buttonHelpLayout = new javax.swing.GroupLayout(buttonHelp);
        buttonHelp.setLayout(buttonHelpLayout);
        buttonHelpLayout.setHorizontalGroup(
            buttonHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonHelpLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(helpLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        buttonHelpLayout.setVerticalGroup(
            buttonHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonHelpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(helpLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout containerTituloLayout = new javax.swing.GroupLayout(containerTitulo);
        containerTitulo.setLayout(containerTituloLayout);
        containerTituloLayout.setHorizontalGroup(
            containerTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerTituloLayout.createSequentialGroup()
                .addGroup(containerTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(containerTituloLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, containerTituloLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(containerTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(containerTituloLayout.createSequentialGroup()
                                .addComponent(perfilYasser, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(containerTituloLayout.createSequentialGroup()
                                .addComponent(perfilCarlos, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 376, Short.MAX_VALUE)
                                .addComponent(perfilKarla)
                                .addGap(14, 14, 14)))))
                .addGap(64, 64, 64))
        );
        containerTituloLayout.setVerticalGroup(
            containerTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerTituloLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(containerTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(perfilKarla, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(perfilCarlos, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                .addGroup(containerTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerTituloLayout.createSequentialGroup()
                        .addComponent(buttonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerTituloLayout.createSequentialGroup()
                        .addComponent(perfilYasser, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addComponent(buttonHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        helpLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        helpLabel.setForeground(new java.awt.Color(78, 88, 97));
        helpLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        helpLabel.setText("Laboratorio 6 AED");

        helpLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        helpLabel2.setForeground(new java.awt.Color(78, 88, 97));
        helpLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        helpLabel2.setText("Generador de arboles binarios");

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(uni, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(helpLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(helpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(containerTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(uni, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(helpLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127)
                .addComponent(helpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(containerTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(container, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonIniciarMouseClicked
        // TODO add your handling code here:
        ArbolBinario frame = new ArbolBinario();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_buttonIniciarMouseClicked

    private void buttonIniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonIniciarMouseEntered
        // TODO add your handling code here:
        buttonIniciar.setBackground(hover);
    }//GEN-LAST:event_buttonIniciarMouseEntered

    private void buttonIniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonIniciarMouseExited
        // TODO add your handling code here:
        buttonIniciar.setBackground(secundary);
    }//GEN-LAST:event_buttonIniciarMouseExited

    private void buttonHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHelpMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "DESCRIPCION DEL PROGRAMA");
    }//GEN-LAST:event_buttonHelpMouseClicked

    private void buttonHelpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHelpMouseEntered
        // TODO add your handling code here:
        buttonHelp.setBackground(hover);
    }//GEN-LAST:event_buttonHelpMouseEntered

    private void buttonHelpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHelpMouseExited
        // TODO add your handling code here:
        buttonHelp.setBackground(secundary);
    }//GEN-LAST:event_buttonHelpMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Presentacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Clases.PanelRound buttonHelp;
    private Clases.PanelRound buttonIniciar;
    private javax.swing.JPanel container;
    private Clases.PanelRound containerTitulo;
    private javax.swing.JLabel helpLabel;
    private javax.swing.JLabel helpLabel1;
    private javax.swing.JLabel helpLabel2;
    private javax.swing.JLabel iniciarLabel;
    private javax.swing.JLabel perfilCarlos;
    private javax.swing.JLabel perfilKarla;
    private javax.swing.JLabel perfilYasser;
    private javax.swing.JLabel uni;
    // End of variables declaration//GEN-END:variables
}
